"use client";
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Instrument={id:string;tag_no:string;name:string};
type Event={id:string;instrument_id:string;calibration_date:string;review_status:string};
type Cert={id:string;instrument_id:string|null;calibration_event_id:string|null;kind:string;certificate_no:string|null;issue_date:string|null;expiry_date:string|null;external_url:string|null;file_path:string|null;notes:string|null};
const blank={instrument_id:"",calibration_event_id:"",kind:"calibration",certificate_no:"",issue_date:"",expiry_date:"",external_url:"",notes:""};
export default function Certificates(){
 const s=useMemo(()=>createClient(),[]),[rows,setRows]=useState<Cert[]>([]),[instruments,setInstruments]=useState<Instrument[]>([]),[events,setEvents]=useState<Event[]>([]),[role,setRole]=useState("viewer"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState<string|null>(null),[form,setForm]=useState(blank),[search,setSearch]=useState(""),[files,setFiles]=useState<Record<string,File|null>>({}),[uploading,setUploading]=useState("");
 const load=useCallback(async()=>{setLoading(true);const [c,i,e,a]=await Promise.all([s.from("certificates").select("id,instrument_id,calibration_event_id,kind,certificate_no,issue_date,expiry_date,external_url,file_path,notes").order("created_at",{ascending:false}),s.from("instruments").select("id,tag_no,name").order("tag_no"),s.from("calibration_events").select("id,instrument_id,calibration_date,review_status").eq("review_status","approved").order("calibration_date",{ascending:false}),s.auth.getUser()]);if(c.error)setMsg(c.error.message);else setRows((c.data??[]) as Cert[]);if(i.error)setMsg(i.error.message);else setInstruments((i.data??[]) as Instrument[]);if(e.error)setMsg(e.error.message);else setEvents((e.data??[]) as Event[]);const uid=a.data.user?.id;if(uid){const p=await s.from("profiles").select("role").eq("id",uid).single();setRole(p.data?.role??"viewer")}setLoading(false)},[s]);
 useEffect(()=>{void load()},[load]);
 const canManage=role==="admin"||role==="manager";
 const instrument=(id:string|null)=>instruments.find(x=>x.id===id);
 const filtered=rows.filter(r=>[r.certificate_no,instrument(r.instrument_id)?.tag_no,r.kind].join(" ").toLowerCase().includes(search.toLowerCase()));
 const eventOptions=events.filter(e=>e.instrument_id===form.instrument_id);
 function beginEdit(c:Cert){setEditing(c.id);setForm({instrument_id:c.instrument_id??"",calibration_event_id:c.calibration_event_id??"",kind:c.kind,certificate_no:c.certificate_no??"",issue_date:c.issue_date??"",expiry_date:c.expiry_date??"",external_url:c.external_url??"",notes:c.notes??""});setOpen(true);setMsg("")}
 async function upload(c:Cert){const file=files[c.id];if(!file||uploading||!canManage)return;if(file.type!=="application/pdf"||file.size>10*1024*1024){setMsg("Select a PDF file no larger than 10 MB.");return}setUploading(c.id);setMsg("");const path=c.id+"/"+Date.now()+"-"+file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const result=await s.storage.from("calibration-certificates").upload(path,file,{contentType:"application/pdf",upsert:false});if(result.error){setMsg("Upload failed: "+result.error.message+". Check whether the storage SQL migration has been run.");setUploading("");return}const update=await s.from("certificates").update({file_path:path}).eq("id",c.id);if(update.error){await s.storage.from("calibration-certificates").remove([path]);setMsg("Document could not be linked: "+update.error.message);setUploading("");return}setFiles(x=>({...x,[c.id]:null}));setUploading("");setMsg("PDF uploaded successfully.");await load()}
 async function viewFile(c:Cert){if(!c.file_path)return;const result=await s.storage.from("calibration-certificates").createSignedUrl(c.file_path,60);if(result.error){setMsg(result.error.message);return}window.open(result.data.signedUrl,"_blank","noopener,noreferrer")}
 async function save(e:FormEvent){e.preventDefault();if(saving||!canManage)return;setSaving(true);setMsg("");if(form.expiry_date&&form.issue_date&&form.expiry_date<form.issue_date){setSaving(false);setMsg("Expiry date cannot precede issue date.");return}if(form.calibration_event_id&&!events.some(x=>x.id===form.calibration_event_id&&x.instrument_id===form.instrument_id)){setSaving(false);setMsg("Select an approved calibration event for this instrument.");return}const {data:{user}}=await s.auth.getUser();const payload={instrument_id:form.instrument_id,calibration_event_id:form.calibration_event_id||null,kind:form.kind,certificate_no:form.certificate_no.trim(),issue_date:form.issue_date||null,expiry_date:form.expiry_date||null,external_url:form.external_url.trim()||null,notes:form.notes.trim()||null};const result=editing?await s.from("certificates").update(payload).eq("id",editing):await s.from("certificates").insert({...payload,created_by:user?.id??null});setSaving(false);if(result.error){setMsg(result.error.message);return}setOpen(false);setEditing(null);setForm(blank);await load()}
 return <main className="content"><header><div><p className="eyebrow">DOCUMENT CONTROL</p><h1>Calibration Certificates</h1><p>Register certificate references and validity information for traceability.</p></div>{canManage&&<button type="button" onClick={()=>{setOpen(!open);setEditing(null);setForm(blank);setMsg("")}}>{open?"Close":"+ Add certificate"}</button>}</header>
 {msg&&<p className="notice" role="status">{msg}</p>}
 {open&&canManage&&<form className="panel" onSubmit={save} style={{marginBottom:20}}><h2>{editing?"Edit certificate":"Register certificate"}</h2><div className="formGrid"><label>Instrument<select required value={form.instrument_id} onChange={e=>setForm({...form,instrument_id:e.target.value,calibration_event_id:""})}><option value="">Select instrument</option>{instruments.map(i=><option value={i.id} key={i.id}>{i.tag_no} — {i.name}</option>)}</select></label><label>Approved calibration (optional)<select value={form.calibration_event_id} onChange={e=>setForm({...form,calibration_event_id:e.target.value})}><option value="">Not linked</option>{eventOptions.map(e=><option value={e.id} key={e.id}>{e.calibration_date} — {e.id.slice(0,8)}</option>)}</select></label><label>Certificate type<select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}>{["calibration","verification","inspection","other"].map(x=><option value={x} key={x}>{x}</option>)}</select></label><label>Certificate number<input required value={form.certificate_no} onChange={e=>setForm({...form,certificate_no:e.target.value})}/></label><label>Issue date<input type="date" value={form.issue_date} onChange={e=>setForm({...form,issue_date:e.target.value})}/></label><label>Expiry date<input type="date" value={form.expiry_date} onChange={e=>setForm({...form,expiry_date:e.target.value})}/></label><label>Certificate document URL<input type="url" placeholder="https://..." value={form.external_url} onChange={e=>setForm({...form,external_url:e.target.value})}/></label></div><label>Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><p><small>Register only genuine certificates. A certificate entry is not proof of an approved calibration unless linked to the supporting approved event and authentic document.</small></p><button type="submit" disabled={saving}>{saving?"Saving…":editing?"Update certificate":"Save certificate"}</button></form>}
 <section className="toolbar"><input placeholder="Search certificate number or instrument tag…" value={search} onChange={e=>setSearch(e.target.value)}/><span>{filtered.length} certificates</span></section>
 <section className="panel tablePanel">{loading?<div className="empty">Loading certificates…</div>:filtered.length?<div className="tableWrap"><table><thead><tr><th>Certificate</th><th>Instrument</th><th>Type</th><th>Issued</th><th>Expiry</th><th>Calibration link</th><th>Document</th><th>Upload PDF</th><th>PDF</th><th></th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><b>{c.certificate_no??"—"}</b></td><td>{instrument(c.instrument_id)?.tag_no??"—"}</td><td>{c.kind}</td><td>{c.issue_date??"—"}</td><td>{c.expiry_date??"—"}</td><td>{c.calibration_event_id?"Linked":"Not linked"}</td><td>{c.file_path?<button type="button" onClick={()=>viewFile(c)}>View stored PDF</button>:c.external_url&&/^https:\/\//i.test(c.external_url)?<a href={c.external_url} target="_blank" rel="noopener noreferrer">Open document ↗</a>:"No document"}</td><td>{canManage&&<div><input aria-label={"PDF for "+(c.certificate_no??c.id)} type="file" accept="application/pdf,.pdf" onChange={e=>setFiles(x=>({...x,[c.id]:e.target.files?.[0]??null}))}/><button type="button" disabled={!files[c.id]||!!uploading} onClick={()=>upload(c)}>{uploading===c.id?"Uploading…":"Upload"}</button></div>}</td><td>{c.calibration_event_id?<Link href={"/workspace/certificates/"+c.id+"/print"}>Print / PDF</Link>:"—"}</td><td>{canManage&&<button type="button" onClick={()=>beginEdit(c)}>Edit</button>}</td></tr>)}</tbody></table></div>:<div className="empty">No certificates registered.<small>Add certificates for your real instruments when documentation is available.</small></div>}</section>
 <p><small>PDF documents are stored in a private bucket and opened using short-lived signed links after the storage migration is applied. Approved, linked calibration records can be printed or saved as PDF using your browser. The printout is not digitally signed or accredited.</small></p></main>;
}