"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Event={id:string;instrument_id:string;request_id:string|null;calibration_date:string;result:string;as_found_summary:string|null;as_left_summary:string|null;procedure_reference:string|null;comments:string|null;approved_at:string|null;approved_by:string|null;review_status:string;review_notes:string|null;reviewed_at:string|null;reviewed_by:string|null;technician_id:string|null;instruments:{tag_no:string;name:string}|{tag_no:string;name:string}[]|null};
export default function Reviews(){
 const s=useMemo(()=>createClient(),[]),[rows,setRows]=useState<Event[]>([]),[role,setRole]=useState("viewer"),[userId,setUserId]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[msg,setMsg]=useState(""),[showAll,setShowAll]=useState(false),[notes,setNotes]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{setLoading(true);const [auth,r]=await Promise.all([s.auth.getUser(),s.from("calibration_events").select("id,instrument_id,request_id,calibration_date,result,as_found_summary,as_left_summary,procedure_reference,comments,approved_at,approved_by,review_status,review_notes,reviewed_at,reviewed_by,technician_id,instruments(tag_no,name)").order("calibration_date",{ascending:false})]);const uid=auth.data.user?.id??"";setUserId(uid);if(uid){const p=await s.from("profiles").select("role").eq("id",uid).single();setRole(p.data?.role??"viewer")}if(r.error)setMsg(r.error.message);else setRows((r.data??[]) as Event[]);setLoading(false)},[s]);
 useEffect(()=>{void load()},[load]);
 const canReview=role==="admin"||role==="manager";
 const visible=rows.filter(x=>showAll||x.review_status==="submitted");
 async function reject(e:Event){if(!canReview||!userId||e.review_status!=="submitted"||busy)return;if(e.technician_id===userId){setMsg("You cannot review your own calibration.");return}const reason=(notes[e.id]??"").trim();if(reason.length<10){setMsg("A rejection reason of at least 10 characters is required.");return}if(!window.confirm("Reject this calibration and return it for correction?"))return;setBusy(e.id);setMsg("");const {data,error}=await s.from("calibration_events").update({review_status:"rejected",review_notes:reason,reviewed_at:new Date().toISOString(),reviewed_by:userId}).eq("id",e.id).eq("review_status","submitted").select("id");if(error||!data?.length){setMsg(error?.message??"This record was already reviewed.");setBusy("");return}setMsg("Calibration rejected. The technician can correct and resubmit it.");setBusy("");await load()}
 async function approve(e:Event){if(!canReview||!userId||e.review_status!=="submitted"||busy)return;if(e.technician_id===userId){setMsg("You cannot approve a calibration you performed. Ask another authorized reviewer.");return}if(!window.confirm("Approve this calibration record? Verify its results and supporting evidence first."))return;setBusy(e.id);setMsg("");const {data,error}=await s.from("calibration_events").update({approved_by:userId,approved_at:new Date().toISOString(),review_status:"approved",reviewed_at:new Date().toISOString(),reviewed_by:userId,review_notes:notes[e.id]?.trim()||null}).eq("id",e.id).eq("review_status","submitted").is("approved_at",null).select("id");if(error){setMsg(error.message);setBusy("");return}if(!data?.length){setMsg("This calibration may have been reviewed already. Refresh the page.");setBusy("");await load();return}if(e.request_id){const r=await s.from("calibration_requests").update({status:"completed",completed_at:new Date().toISOString()}).eq("id",e.request_id).eq("calibration_event_id",e.id);if(r.error)setMsg("Calibration approved, but work order could not be completed: "+r.error.message);else setMsg("Calibration approved and work order completed.");}else setMsg("Calibration approved.");setBusy("");await load()}
 return <main className="content"><header><div><p className="eyebrow">QUALITY ASSURANCE</p><h1>Calibration Review</h1><p>Review recorded calibration results before approving them.</p></div><Link href="/workspace/requests">Work orders →</Link></header>
 <section className="cards"><article><div><span>Awaiting review</span><strong>{rows.filter(x=>x.review_status==="submitted").length}</strong></div></article><article><div><span>Approved</span><strong>{rows.filter(x=>x.review_status==="approved").length}</strong></div></article></section>
 <p><small>Only administrators and managers can approve records. Approval is separate from recording measurements. Review comments and rejection decisions are recorded with reviewer and timestamp.</small></p>
 {msg&&<div className="notice" role="status">{msg}</div>}<label className="check"><input type="checkbox" checked={showAll} onChange={e=>setShowAll(e.target.checked)}/> Include approved records</label>
 <section className="panel tablePanel">{loading?<div className="empty">Loading calibration records…</div>:visible.length?<div className="tableWrap"><table><thead><tr><th>Instrument</th><th>Calibrated</th><th>Result</th><th>Procedure</th><th>As found / as left</th><th>Review</th><th>Action</th></tr></thead><tbody>{visible.map(e=>{const inst=Array.isArray(e.instruments)?e.instruments[0]:e.instruments;return <tr key={e.id}><td><b>{inst?.tag_no??"—"}</b><small className="cellSub">{inst?.name??""}</small></td><td>{e.calibration_date}</td><td>{e.result}</td><td>{e.procedure_reference??"—"}</td><td><details><summary>View results</summary><p><b>As found:</b> {e.as_found_summary??"—"}</p><p><b>As left:</b> {e.as_left_summary??"—"}</p><p><b>Comments:</b> {e.comments??"—"}</p></details></td><td>{e.review_status+(e.reviewed_at?" "+new Date(e.reviewed_at).toLocaleDateString():"")}</td><td>{e.review_status!=="submitted"?<><small>{e.review_notes??""}</small> <Link href={"/workspace/instruments/"+e.instrument_id}>View</Link></>:canReview?<button type="button" disabled={!!busy||e.technician_id===userId} title={e.technician_id===userId?"Self-approval is not permitted":""} onClick={()=>approve(e)}>{busy===e.id?"Working…":"Approve"}</button><textarea placeholder="Review comments (required for rejection)" aria-label="Review comments" value={notes[e.id]??""} onChange={x=>setNotes(v=>({...v,[e.id]:x.target.value}))}/><button type="button" disabled={!!busy||e.technician_id===userId} onClick={()=>reject(e)}>Reject</button>: "Awaiting reviewer"}</td></tr>})}</tbody></table></div>:<div className="empty">No calibration records awaiting review.</div>}</section></main>;
}