"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
export type Alert={key:string;type:"Calibration"|"Certificate";title:string;date:string;link:string;delta:number};
const OPTIONS=[7,14,30,60,90] as const;
export default function NotificationList({alerts}:{alerts:Alert[]}){
 const [threshold,setThreshold]=useState(30),[calibration,setCalibration]=useState(true),[certificate,setCertificate]=useState(true),[ready,setReady]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem("caldashpro-alert-preferences-v1");if(raw){const saved=JSON.parse(raw);if(OPTIONS.includes(saved.threshold))setThreshold(saved.threshold);if(typeof saved.calibration==="boolean")setCalibration(saved.calibration);if(typeof saved.certificate==="boolean")setCertificate(saved.certificate)}}catch{}setReady(true)},[]);
 function persist(next:{threshold:number;calibration:boolean;certificate:boolean}){setThreshold(next.threshold);setCalibration(next.calibration);setCertificate(next.certificate);try{localStorage.setItem("caldashpro-alert-preferences-v1",JSON.stringify(next))}catch{}}
 const visible=useMemo(()=>alerts.filter(a=>a.delta<=threshold&&((a.type==="Calibration"&&calibration)||(a.type==="Certificate"&&certificate))).sort((a,b)=>a.delta-b.delta),[alerts,threshold,calibration,certificate]);
 const past=visible.filter(a=>a.delta<0).length,upcoming=visible.filter(a=>a.delta>=0).length;
 return <><section className="panel" style={{marginBottom:20}}><h2>Reminder preferences</h2><p>Choose which deadlines appear in your personal notification center.</p><div className="formGrid"><label>Advance warning<select value={threshold} onChange={e=>persist({threshold:Number(e.target.value),calibration,certificate})}>{OPTIONS.map(n=><option key={n} value={n}>{n} days before due</option>)}</select></label><label><input type="checkbox" checked={calibration} onChange={e=>persist({threshold,calibration:e.target.checked,certificate})}/> Instrument calibrations</label><label><input type="checkbox" checked={certificate} onChange={e=>persist({threshold,calibration,certificate:e.target.checked})}/> Certificate expiry</label></div><p><small>Preferences are saved only in this browser, not to your account. Past-due items remain visible whenever their category is enabled. No email or Telegram messages are sent.</small></p></section>
 <section className="cards"><article><div><span>Past due</span><strong>{ready?past:"…"}</strong></div></article><article><div><span>Upcoming deadlines</span><strong>{ready?upcoming:"…"}</strong></div></article><article><div><span>Total alerts</span><strong>{ready?visible.length:"…"}</strong></div></article></section>
 <section className="panel tablePanel" style={{marginTop:20}}>{!ready?<div className="empty">Loading your preferences…</div>:visible.length?<div className="tableWrap"><table><thead><tr><th>Priority</th><th>Type</th><th>Item</th><th>Deadline</th><th>Action</th></tr></thead><tbody>{visible.map(a=><tr key={a.key}><td><span className={"status "+(a.delta<0?"overdue":"due_soon")}>{a.delta<0?Math.abs(a.delta)+" days overdue":a.delta===0?"Due today":a.delta+" days remaining"}</span></td><td>{a.type}</td><td><b>{a.title}</b></td><td>{a.date}</td><td><Link href={a.link}>Review →</Link></td></tr>)}</tbody></table></div>:<div className="empty">No alerts match your selected preferences.</div>}</section></>;
}