"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Instrument={id:string;tag_no:string;name:string;next_due_date:string|null;state:string};
type Request={id:string;instrument_id:string;due_date:string|null;priority:string;status:string;source:string;notes:string|null;assigned_to:string|null;instruments:{tag_no:string;name:string}|{tag_no:string;name:string}[]|null};
type Profile={id:string;full_name:string;role:string;active:boolean};
const dateDays=(value:string)=>Math.round((Date.parse(value+"T00:00:00Z")-Date.parse(new Date().toISOString().slice(0,10)+"T00:00:00Z"))/86400000);
export default function Requests(){
 const s=useMemo(()=>createClient(),[]);
 const [rows,setRows]=useState<Request[]>([]),[instruments,setInstruments]=useState<Instrument[]>([]),[staff,setStaff]=useState<Profile[]>([]),[role,setRole]=useState("viewer"),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[selected,setSelected]=useState(""),[assignee,setAssignee]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{setLoading(true);const [r,i,p,auth]=await Promise.all([s.from("calibration_requests").select("id,instrument_id,due_date,priority,status,source,notes,assigned_to,instruments(tag_no,name)").order("due_date",{ascending:true}),s.from("instrument_calibration_status").select("id,tag_no,name,next_due_date,state").eq("state","active"),s.from("profiles").select("id,full_name,role,active").eq("active",true),s.auth.getUser()]);if(r.error)setMsg(r.error.message);else setRows((r.data??[]) as Request[]);if(i.error)setMsg(i.error.message);else setInstruments((i.data??[]) as Instrument[]);setStaff((p.data??[]) as Profile[]);const uid=auth.data.user?.id;if(uid){const pr=await s.from("profiles").select("role").eq("id",uid).single();setRole(pr.data?.role??"viewer")}setLoading(false)},[s]);
 useEffect(()=>{void load()},[load]);
 const canManage=role==="admin"||role==="manager";
 const openIds=new Set(rows.filter(r=>r.status!=="completed"&&r.status!=="cancelled").map(r=>r.instrument_id));
 const candidates=instruments.filter(i=>i.next_due_date&&dateDays(i.next_due_date)<=30&&!openIds.has(i.id)).sort((a,b)=>(a.next_due_date??"").localeCompare(b.next_due_date??""));
 async function generate(){if(!canManage)return;setBusy(true);setMsg("");const {data:{user}}=await s.auth.getUser();const payload=candidates.map(i=>({instrument_id:i.id,due_date:i.next_due_date,priority:dateDays(i.next_due_date!)<0?"critical":dateDays(i.next_due_date!)<=7?"high":"normal",source:"automatic",requested_by:user?.id??null,notes:"Generated from calibration schedule; verify instrument details before execution."}));if(!payload.length){setMsg("No eligible instruments without an open request.");setBusy(false);return}const {error}=await s.from("calibration_requests").insert(payload);setBusy(false);setMsg(error?error.message:`Created ${payload.length} calibration requests.`);await load()}
 async function createManual(){if(!canManage||!selected)return;setBusy(true);setMsg("");const i=instruments.find(x=>x.id===selected);const {data:{user}}=await s.auth.getUser();const {error}=await s.from("calibration_requests").insert({instrument_id:selected,due_date:i?.next_due_date??null,priority:"normal",source:"manual",requested_by:user?.id??null});setBusy(false);setMsg(error?error.message:"Calibration request created.");if(!error)setSelected("");await load()}
 async function assign(r:Request){if(!canManage)return;setBusy(true);setMsg("");const id=assignee[r.id]??r.assigned_to??"";const {error}=await s.from("calibration_requests").update({assigned_to:id||null,status:id?"assigned":"open"}).eq("id",r.id).in("status",["open","assigned"]);setBusy(false);setMsg(error?error.message:"Assignment updated.");await load()}
 return <main className="content"><header><div><p className="eyebrow">WORK ORDERS</p><h1>Calibration Requests</h1><p>Generate, assign and track calibration work orders.</p></div><Link href="/workspace/schedule">View schedule →</Link></header>
 {msg&&<div className="notice" role="status">{msg}</div>}
 {canManage&&<section className="panel" style={{marginBottom:18}}><h2>Create calibration work</h2><p>{candidates.length} active instruments are due or due within 30 days without an open request.</p><button type="button" disabled={busy||loading||!candidates.length} onClick={generate}>{busy?"Working…":`Generate ${candidates.length} due requests`}</button><p><small>Requests are created only when you select Generate. Completed and cancelled requests do not prevent future work orders.</small></p><div className="formGrid"><label>Manual request<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select an instrument</option>{instruments.map(i=><option value={i.id} key={i.id}>{i.tag_no} — {i.name}</option>)}</select></label></div><button type="button" disabled={busy||!selected} onClick={createManual}>Create manual request</button></section>}
 <section className="panel tablePanel">{loading?<div className="empty">Loading calibration requests…</div>:rows.length?<div className="tableWrap"><table><thead><tr><th>Instrument</th><th>Due</th><th>Priority</th><th>Status</th><th>Assigned technician</th><th>Source</th><th>Action</th></tr></thead><tbody>{rows.map(r=>{const inst=Array.isArray(r.instruments)?r.instruments[0]:r.instruments;return <tr key={r.id}><td><b>{inst?.tag_no??"—"}</b><small className="cellSub">{inst?.name??""}</small></td><td>{r.due_date??"—"}</td><td>{r.priority}</td><td><span className={"status "+r.status}>{r.status.replaceAll("_"," ")}</span></td><td>{canManage&&(r.status==="open"||r.status==="assigned")?<div><select value={assignee[r.id]??r.assigned_to??""} onChange={e=>setAssignee(x=>({...x,[r.id]:e.target.value}))}><option value="">Unassigned</option>{staff.filter(p=>p.role==="technician"||p.role==="manager"||p.role==="admin").map(p=><option value={p.id} key={p.id}>{p.full_name||p.id.slice(0,8)}</option>)}</select><button type="button" disabled={busy} onClick={()=>assign(r)}>Save</button></div>:staff.find(p=>p.id===r.assigned_to)?.full_name??"Unassigned"}</td><td>{r.source}</td><td>{r.status!=="completed"&&r.status!=="cancelled"&&<Link href={"/workspace/calibrate/"+r.id}>Start</Link>}</td></tr>})}</tbody></table></div>:<div className="empty">No calibration requests.<small>Generate requests from the schedule or create one manually.</small></div>}</section>
 </main>;
}