"use client";
import Link from "next/link";import {FormEvent,useEffect,useMemo,useState} from "react";import {createClient} from "@/lib/supabase/client";
type Ref={id:string;name:string;area_id?:string|null};type Instrument={id:string;tag_no:string;name:string;serial_no:string|null;manufacturer:string|null;model:string|null;engineering_unit:string|null;calibration_interval_months:number|null;next_due_date:string|null;calibration_status:string;area_id:string|null;location_id:string|null;instrument_group_id:string|null};
const blank={tag_no:"",name:"",serial_no:"",manufacturer:"",model:"",engineering_unit:"",calibration_interval_months:"",next_due_date:"",area_id:"",location_id:"",instrument_group_id:""};
export default function Instruments(){const[rows,setRows]=useState<Instrument[]>([]),[areas,setAreas]=useState<Ref[]>([]),[locations,setLocations]=useState<Ref[]>([]),[groups,setGroups]=useState<Ref[]>([]),[q,setQ]=useState(""),[status,setStatus]=useState("All"),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState(""),[form,setForm]=useState(blank);const s=useMemo(()=>createClient(),[]);
async function load(){setLoading(true);const[a,l,g,i]=await Promise.all([s.from("areas").select("id,name").eq("active",true).order("name"),s.from("locations").select("id,name,area_id").eq("active",true).order("name"),s.from("instrument_groups").select("id,name").eq("active",true).order("name"),s.from("instrument_calibration_status").select("id,tag_no,name,serial_no,manufacturer,model,engineering_unit,calibration_interval_months,next_due_date,calibration_status,area_id,location_id,instrument_group_id").order("tag_no")]);setAreas(a.data??[]);setLocations(l.data??[]);setGroups(g.data??[]);if(i.error)setMsg(i.error.message);else {setRows((i.data??[]) as Instrument[]);setMsg("")}setLoading(false)}
useEffect(()=>{load()},[]);
async function add(e:FormEvent){e.preventDefault();setMsg("Saving...");setSaving(true);const{data:{user}}=await s.auth.getUser();const payload={tag_no:form.tag_no.trim(),name:form.name.trim(),serial_no:form.serial_no||null,manufacturer:form.manufacturer||null,model:form.model||null,engineering_unit:form.engineering_unit||null,calibration_interval_months:form.calibration_interval_months?Number(form.calibration_interval_months):null,next_due_date:form.next_due_date||null,area_id:form.area_id||null,location_id:form.location_id||null,instrument_group_id:form.instrument_group_id||null,created_by:user?.id??null};const{error}=await s.from("instruments").insert(payload);if(error){setMsg(error.message);setSaving(false);return}setSaving(false);setForm(blank);setOpen(false);setMsg("");await load()}
const filtered=rows.filter(r=>{const text=(r.tag_no+" "+r.name+" "+(r.serial_no??"")+" "+(r.manufacturer??"")).toLowerCase();return text.includes(q.toLowerCase())&&(status==="All"||r.calibration_status===status)});
const ref=(xs:Ref[],id:string|null)=>xs.find(x=>x.id===id)?.name??"—";const allowedLocations=locations.filter(x=>!form.area_id||x.area_id===form.area_id);
return <main className="content"><header><div><p className="eyebrow">CALIBRATION MANAGEMENT</p><h1>Instruments</h1><p>Manage your instrument register, ownership and calibration compliance.</p></div><button onClick={()=>setOpen(!open)}>{open?"Close":"+ Add instrument"}</button></header>
{open&&<form className="panel instrumentForm" onSubmit={add}><h2>New instrument</h2><div className="formGrid"><label>Tag number<input required value={form.tag_no} onChange={e=>setForm({...form,tag_no:e.target.value})}/></label><label>Instrument name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Serial number<input value={form.serial_no} onChange={e=>setForm({...form,serial_no:e.target.value})}/></label><label>Manufacturer<input value={form.manufacturer} onChange={e=>setForm({...form,manufacturer:e.target.value})}/></label><label>Model<input value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></label><label>Engineering unit<input value={form.engineering_unit} onChange={e=>setForm({...form,engineering_unit:e.target.value})}/></label><label>Area<select value={form.area_id} onChange={e=>setForm({...form,area_id:e.target.value,location_id:""})}><option value="">Select area</option>{areas.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Location<select value={form.location_id} onChange={e=>setForm({...form,location_id:e.target.value})}><option value="">Select location</option>{allowedLocations.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Instrument group<select value={form.instrument_group_id} onChange={e=>setForm({...form,instrument_group_id:e.target.value})}><option value="">Select group</option>{groups.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Interval (months)<input type="number" min="1" value={form.calibration_interval_months} onChange={e=>setForm({...form,calibration_interval_months:e.target.value})}/></label><label>Next due date<input type="date" value={form.next_due_date} onChange={e=>setForm({...form,next_due_date:e.target.value})}/></label></div><button type="submit" disabled={saving}>{saving?"Saving…":"Save instrument"}</button>{msg&&<small>{msg}</small>}</form>}
{!open&&msg&&<p role="alert" className="notice">{msg}</p>}<section className="toolbar"><div className="filters"><input placeholder="Search tag, name, serial or manufacturer..." value={q} onChange={e=>setQ(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}>{["All","Valid","Expiring Soon","Critical","Overdue","No Due Date"].map(x=><option key={x}>{x}</option>)}</select></div><span>{filtered.length} instruments</span></section>
<section className="panel tablePanel">{loading?<div className="empty">Loading instruments…</div>:filtered.length===0?<div className="empty">No instruments found.<small>Add an instrument or adjust your filters.</small></div>:<div className="tableWrap"><table><thead><tr><th>Tag</th><th>Instrument</th><th>Area / Location</th><th>Group</th><th>Next due</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(i=><tr key={i.id}><td><b>{i.tag_no}</b></td><td>{i.name}<small className="cellSub">{i.serial_no??"No serial"}</small></td><td>{ref(areas,i.area_id)}<small className="cellSub">{ref(locations,i.location_id)}</small></td><td>{ref(groups,i.instrument_group_id)}</td><td>{i.next_due_date??"—"}</td><td><span className={"status "+i.calibration_status.toLowerCase().replaceAll(" ","-")}>{i.calibration_status}</span></td><td><Link href={"/workspace/instruments/"+i.id}>View</Link></td></tr>)}</tbody></table></div>}</section></main>}