"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Instrument={id:string;tag_no:string;name:string;serial_no:string|null;manufacturer:string|null;model:string|null;engineering_unit:string|null;calibration_interval_months:number|null;next_due_date:string|null;calibration_status:string};
const blank={tag_no:"",name:"",serial_no:"",manufacturer:"",model:"",engineering_unit:"",calibration_interval_months:"",next_due_date:""};
export default function Instruments(){
 const [rows,setRows]=useState<Instrument[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[msg,setMsg]=useState(""),[form,setForm]=useState(blank);
 const s=useMemo(()=>createClient(),[]);
 async function load(){const{data,error}=await s.from("instrument_calibration_status").select("id,tag_no,name,serial_no,manufacturer,model,engineering_unit,calibration_interval_months,next_due_date,calibration_status").order("tag_no");if(error)setMsg(error.message);else setRows((data??[]) as Instrument[])}
 useEffect(()=>{load()},[]);
 async function add(e:FormEvent){e.preventDefault();setMsg("Saving...");const payload={tag_no:form.tag_no.trim(),name:form.name.trim(),serial_no:form.serial_no||null,manufacturer:form.manufacturer||null,model:form.model||null,engineering_unit:form.engineering_unit||null,calibration_interval_months:form.calibration_interval_months?Number(form.calibration_interval_months):null,next_due_date:form.next_due_date||null};const{error}=await s.from("instruments").insert(payload);if(error){setMsg(error.message);return}setForm(blank);setOpen(false);setMsg("");await load()}
 const filtered=rows.filter(r=>(r.tag_no+" "+r.name+" "+(r.serial_no??"")).toLowerCase().includes(q.toLowerCase()));
 return <main className="content"><header><div><p className="eyebrow">CALIBRATION MANAGEMENT</p><h1>Instruments</h1><p>Manage the instrument register and live calibration compliance.</p></div><button onClick={()=>setOpen(!open)}>+ Add instrument</button></header>
 {open&&<form className="panel instrumentForm" onSubmit={add}><h2>New instrument</h2><div className="formGrid"><label>Tag number<input required value={form.tag_no} onChange={e=>setForm({...form,tag_no:e.target.value})}/></label><label>Instrument name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Serial number<input value={form.serial_no} onChange={e=>setForm({...form,serial_no:e.target.value})}/></label><label>Manufacturer<input value={form.manufacturer} onChange={e=>setForm({...form,manufacturer:e.target.value})}/></label><label>Model<input value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></label><label>Engineering unit<input value={form.engineering_unit} onChange={e=>setForm({...form,engineering_unit:e.target.value})}/></label><label>Interval (months)<input type="number" min="1" value={form.calibration_interval_months} onChange={e=>setForm({...form,calibration_interval_months:e.target.value})}/></label><label>Next due date<input type="date" value={form.next_due_date} onChange={e=>setForm({...form,next_due_date:e.target.value})}/></label></div><button type="submit">Save instrument</button>{msg&&<small>{msg}</small>}</form>}
 <section className="toolbar"><input placeholder="Search tag, name or serial..." value={q} onChange={e=>setQ(e.target.value)}/><span>{filtered.length} instruments</span></section>
 <section className="panel tablePanel">{filtered.length===0?<div className="empty">No instruments found.<small>Add an instrument or adjust your search.</small></div>:<div className="tableWrap"><table><thead><tr><th>Tag</th><th>Instrument</th><th>Serial</th><th>Manufacturer</th><th>Next due</th><th>Status</th></tr></thead><tbody>{filtered.map(i=><tr key={i.id}><td><b>{i.tag_no}</b></td><td>{i.name}</td><td>{i.serial_no??"—"}</td><td>{i.manufacturer??"—"}</td><td>{i.next_due_date??"—"}</td><td><span className={"status "+i.calibration_status.toLowerCase().replaceAll(" ","-")}>{i.calibration_status}</span></td></tr>)}</tbody></table></div>}</section></main>
}